### ISSUE TITLE
make DECT and other things totally switchable

### ISSUE THREAD

**Issue by anykraus** [jcf-fjs-helfersystem/engelsystem#13]
Some html output and SQL queries have currently things hardcoded not needed for FJS 2017 into the source code:
e.g.: Commit fdb757f5c3544ed27818cb2cbff7ffcef28056da removes DECT and Jabber
There should be more commits where this happened, hopefully they are marked with something like
`// !! MANUELL entfernt !!`

Using/not using this part should depend on the  setting of the global $enable_dect variable from config/config.php.

**Comment by anykraus** [comment]
This issue does not matter for FJS 2017, but for long term: Using this on other events.

**Comment by Nihlatak** [comment]
issue is now resolved with the latest commits in the FJS-2017-Testbranch

**Comment by anykraus** [comment]
fixed with commit e2e1040bcab0d9fc339e1b6dc19e0b950cf5f618

**Comment by anykraus** [comment]
This is a commit where a lot happened in the user settings page https://github.com/jcf-fjs-helfersystem/engelsystem/commit/634d0db514aa67d22a99e15a0da85518fe2a5c09
