### ISSUE TITLE
remove unused variables

### ISSUE THREAD

**Issue by anykraus** [jcf-fjs-helfersystem/engelsystem#17]
$enable_angeltypedescription
is defined in /config/config.default.php
and referenced as global in \includes\pages\guest_login.php
but it is never actually used. It has probably been superseded by $enable_description_jobs as it turns on and off the indication of angeltype/helpertype during registration.

**Comment by Nihlatak** [comment]
the variable was intended to switchable remove the angeltypdescription on the Login-page.
guest_login.php now uses the variable and the angeltypdescriptions are now fully switchable. 
See latest commits in FJS-2017-Testbranch

**Comment by anykraus** [comment]
fixed with pull request #19
953e2f3
